from __future__ import annotations
from _frozen_importlib import BuiltinImporter as __loader__
import collections.abc
import enum
import typing
__all__: list[str] = ['Connector', 'Device', 'Emulator', 'IConnectable', 'Peripheral', 'Register', 'Window', 'get_emulator', 'on_fuzzing_start', 'on_start', 'print', 'register_device', 'register_peripheral', 'register_window']
class Connector:
    def __init__(self, id: str, type: str, callback: collections.abc.Callable[[typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex, bytes], int] = None) -> None:
        ...
    def call_callback(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: bytes) -> int:
        ...
    def set_callback(self, arg0: collections.abc.Callable[[typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex, bytes], int]) -> None:
        ...
class Device(IConnectable):
    def __init__(self) -> None:
        ...
    def draw_node(self) -> None:
        ...
    def init(self) -> None:
        ...
class Emulator:
    def add_breakpoint(self, address: typing.SupportsInt | typing.SupportsIndex, size: typing.SupportsInt | typing.SupportsIndex, callback: collections.abc.Callable[[], None]) -> int:
        ...
    def get_register(self, arg0: Register) -> int:
        ...
    def read_memory(self, address: typing.SupportsInt | typing.SupportsIndex, size: typing.SupportsInt | typing.SupportsIndex) -> typing.Any:
        ...
    def remove_breakpoint(self, handle: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def set_register(self, arg0: Register, arg1: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def stop(self) -> None:
        ...
    def write_memory(self, address: typing.SupportsInt | typing.SupportsIndex, data: bytes) -> bool:
        ...
class IConnectable:
    def register_input_connector(self, arg0: Connector) -> None:
        ...
    def register_output_connector(self, arg0: Connector) -> None:
        ...
class Peripheral(IConnectable):
    def __init__(self) -> None:
        ...
    def init(self) -> None:
        ...
    def read(self, offset: typing.SupportsInt | typing.SupportsIndex, size: typing.SupportsInt | typing.SupportsIndex) -> int:
        ...
    def update(self) -> None:
        ...
    def write(self, offset: typing.SupportsInt | typing.SupportsIndex, size: typing.SupportsInt | typing.SupportsIndex, value: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
class Register(enum.Enum):
    LR: typing.ClassVar[Register]  # value = <Register.LR: 14>
    PC: typing.ClassVar[Register]  # value = <Register.PC: 15>
    R0: typing.ClassVar[Register]  # value = <Register.R0: 0>
    R1: typing.ClassVar[Register]  # value = <Register.R1: 1>
    R10: typing.ClassVar[Register]  # value = <Register.R10: 10>
    R11: typing.ClassVar[Register]  # value = <Register.R11: 11>
    R12: typing.ClassVar[Register]  # value = <Register.R12: 12>
    R2: typing.ClassVar[Register]  # value = <Register.R2: 2>
    R3: typing.ClassVar[Register]  # value = <Register.R3: 3>
    R4: typing.ClassVar[Register]  # value = <Register.R4: 4>
    R5: typing.ClassVar[Register]  # value = <Register.R5: 5>
    R6: typing.ClassVar[Register]  # value = <Register.R6: 6>
    R7: typing.ClassVar[Register]  # value = <Register.R7: 7>
    R8: typing.ClassVar[Register]  # value = <Register.R8: 8>
    R9: typing.ClassVar[Register]  # value = <Register.R9: 9>
    SP: typing.ClassVar[Register]  # value = <Register.SP: 13>
class Window:
    def __init__(self, arg0: str) -> None:
        ...
    def draw(self) -> None:
        ...
    def init(self) -> None:
        ...
def get_emulator() -> Emulator:
    ...
def on_fuzzing_start(arg0: collections.abc.Callable[[Emulator, bytes], None]) -> None:
    ...
def on_start(arg0: collections.abc.Callable[[Emulator], None]) -> None:
    ...
def print(s: str) -> None:
    ...
def register_device(id: str, factory_fn: collections.abc.Callable[[dict], Device]) -> None:
    ...
def register_peripheral(id: str, factory_fn: collections.abc.Callable[[], Peripheral]) -> None:
    ...
def register_window(window: Window) -> None:
    ...
